### PR TITLE
Fix typo & duplicate instructions in Ch. 3

### PR DESCRIPTION
**Pull request by twome**
Feel free to revert the `PurchaseError` change, I just felt it might be useful disambiguation

### CODE REVIEW

**Comment by twome** [comment]
Also sorry for not rebasing to clean up the merges, I haven't learned that yet

**Review by lpil — COMMENTED** [review]
Hello! You've removed the documentation for the accessor syntax. Was that intentional?

**Comment by twome** [comment]
Yep; that paragraph is almost identical to the one from the [previous lesson on accessors](https://tour.gleam.run/data-types/record-accessors/). I figured its presence in the [record updates lesson](https://tour.gleam.run/data-types/record-updates/) was an editing mistake because there aren't any record accessors in the updates lesson, and because and the paragraphs are so similar. Subtle thing to spot without fresh eyes :)

**Review by lpil — APPROVED** [review]
Ah! I understand now. Thank you for the explanation 💜

**Pull request merged**
