### PR TITLE
feat: :lipstick: adds css print media rules for everything page

### LINKED ISSUE #71: Add print styles
Make it so folks can nicely print the [everything page](https://tour.gleam.run/everything/) nicely.

Context: https://github.com/gleam-lang/gleam/discussions/2622#discussioncomment-8915252

### PR DESCRIPTION
**Pull request by xxKeefer**
for /everything page of the tour to be printed as a multi page pdf doc

closes #71

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Brilliant, thank you!

I think I may have a bug though? When I print-preview in firefox it thinks there's only one page and the rest of the content is missing

image

**Comment by lpil** [comment]
oops sorry, I clicked "approve" by mistake

**Comment by xxKeefer** [comment]
Hey there @lpil, Sorry i should have checked FireFox, upon further investigation it appears `@media print` is scuffed on FireFox, I can not get it to respect any of the page break media and it wouldn't even do multiple pages until i chucked a `* { overflow: visible !important; }` on it.

I'm not prepared to go on a deeper dive on this one, this pr at least gives people on chromium browsers an option to print it. 

I should also note i don't have access to a machine that can run safari so i cannot confirm if this works for apple users.

**Comment by lpil** [comment]
I'm afraid we cannot accept browser specific functionality so this cannot be merged.

**Comment by xxKeefer** [comment]
As it turns out, when it's not two in the morning in my local and after a good nights sleeps i was prepared for deep diving. In hindsight of course it should work on all browsers i don't know what i was thinking 🤦🏻 .

**Review by lpil — APPROVED** [review]
Amazing! Thank you so much!

I'm glad you figured it out as I wouldn't know where to start 😁

**Comment by inoas** [comment]
wow this looks so great!

**Pull request merged**
